"""live plane baseline: identity + evidence chain (tranche 1)

Revision ID: 3b45f6f49303
Revises: 
Create Date: 2026-07-22 22:51:45.803179
"""
from alembic import op
import sqlalchemy as sa


revision = '3b45f6f49303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider_league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=32), nullable=True),
    sa.Column('match_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('supports_draw', sa.Boolean(), nullable=True),
    sa.Column('regular_time_only', sa.Boolean(), nullable=True),
    sa.Column('has_group_stage', sa.Boolean(), nullable=True),
    sa.Column('has_knockout_stage', sa.Boolean(), nullable=True),
    sa.Column('model_version', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approved_for_shadow', sa.Boolean(), nullable=False),
    sa.Column('approved_for_real_money', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('endpoint', sa.String(length=160), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_slug', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=80), nullable=False),
    sa.Column('abbrev', sa.String(length=8), nullable=True),
    sa.Column('espn_id', sa.String(length=16), nullable=True),
    sa.Column('api_football_id', sa.Integer(), nullable=True),
    sa.Column('kalshi_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['competition_slug'], ['competition.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_slug', 'canonical_name')
    )
    op.create_table('fixture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_slug', sa.String(length=32), nullable=False),
    sa.Column('provider_fixture_id', sa.String(length=32), nullable=True),
    sa.Column('espn_event_id', sa.String(length=16), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('original_kickoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_kickoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('round', sa.String(length=32), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['competition_slug'], ['competition.slug'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_slug', 'espn_event_id')
    )
    op.create_table('team_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'alias')
    )
    op.create_table('fixture_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.String(length=96), nullable=True),
    sa.Column('new_value', sa.String(length=96), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_slug', sa.String(length=32), nullable=True),
    sa.Column('kalshi_event_ticker', sa.String(length=64), nullable=False),
    sa.Column('series', sa.String(length=24), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('settlement_scope', sa.String(length=24), nullable=True),
    sa.Column('mapped_via', sa.String(length=24), nullable=True),
    sa.Column('mapping_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['competition_slug'], ['competition.slug'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kalshi_event_ticker')
    )
    op.create_table('prediction_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=16), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seconds_before_kickoff', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('canonical', sa.Boolean(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('git_revision', sa.String(length=40), nullable=True),
    sa.Column('simulation_seed', sa.Integer(), nullable=True),
    sa.Column('simulation_count', sa.Integer(), nullable=True),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('team_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('player_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('availability_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('lineup_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('market_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_fixture_canonical_t10', 'prediction_run', ['fixture_id'], unique=True, postgresql_where=sa.text("run_type = 't10' AND canonical IS 1 AND status = 'complete'"), sqlite_where=sa.text("run_type = 't10' AND canonical IS 1 AND status = 'complete'"))
    op.create_table('market_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_event_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=80), nullable=False),
    sa.Column('side_label', sa.String(length=64), nullable=True),
    sa.Column('outcome_key', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['market_event_id'], ['market_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('market_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_contract_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yes_bid_c', sa.Integer(), nullable=True),
    sa.Column('yes_bid_size', sa.Integer(), nullable=True),
    sa.Column('yes_ask_c', sa.Integer(), nullable=True),
    sa.Column('yes_ask_size', sa.Integer(), nullable=True),
    sa.Column('no_bid_c', sa.Integer(), nullable=True),
    sa.Column('no_bid_size', sa.Integer(), nullable=True),
    sa.Column('no_ask_c', sa.Integer(), nullable=True),
    sa.Column('no_ask_size', sa.Integer(), nullable=True),
    sa.Column('last_trade_c', sa.Integer(), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('rules_hash', sa.String(length=64), nullable=True),
    sa.Column('fee_schedule_version', sa.String(length=16), nullable=True),
    sa.Column('source_observation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_contract_id'], ['market_contract.id'], ),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_depth_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_quote_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price_c', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_quote_id'], ['market_quote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=False),
    sa.Column('market_contract_id', sa.Integer(), nullable=True),
    sa.Column('outcome_key', sa.String(length=32), nullable=False),
    sa.Column('raw_probability', sa.Float(), nullable=False),
    sa.Column('anchored_probability', sa.Float(), nullable=True),
    sa.Column('market_quote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_contract_id'], ['market_contract.id'], ),
    sa.ForeignKeyConstraint(['market_quote_id'], ['market_quote.id'], ),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_run_id', 'market_contract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_contract')
    op.drop_table('market_depth_level')
    op.drop_table('market_quote')
    op.drop_table('market_contract')
    op.drop_index('uq_fixture_canonical_t10', table_name='prediction_run', postgresql_where=sa.text("run_type = 't10' AND canonical IS 1 AND status = 'complete'"), sqlite_where=sa.text("run_type = 't10' AND canonical IS 1 AND status = 'complete'"))
    op.drop_table('prediction_run')
    op.drop_table('market_event')
    op.drop_table('fixture_change')
    op.drop_table('team_alias')
    op.drop_table('fixture')
    op.drop_table('team')
    op.drop_table('source_observation')
    op.drop_table('model_version')
    op.drop_table('competition')
    # ### end Alembic commands ###
