"""lineup + availability plane (V8.1 eval Phase 5 / step 6)

player identity, as-of lineup snapshots with provenance, per-player
entries, and the run's frozen input-quality states. New tables +
one nullable column — plain DDL, valid on SQLite and PostgreSQL.

Revision ID: 521bd3137595
Revises: c21ba2ee8df4
Create Date: 2026-07-23
"""
from alembic import op
import sqlalchemy as sa


revision = '521bd3137595'
down_revision = 'c21ba2ee8df4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_slug', sa.String(length=32), nullable=True),
    sa.Column('espn_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=96), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['competition_slug'], ['competition.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_id')
    )
    op.create_table('lineup_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=True),
    sa.Column('parser_version', sa.String(length=16), nullable=True),
    sa.Column('source_observation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('home_confirmed', sa.Boolean(), nullable=True),
    sa.Column('away_confirmed', sa.Boolean(), nullable=True),
    sa.Column('home_formation', sa.String(length=16), nullable=True),
    sa.Column('away_formation', sa.String(length=16), nullable=True),
    sa.Column('home_gk_player_id', sa.Integer(), nullable=True),
    sa.Column('away_gk_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_gk_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['home_gk_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['source_observation_id'], ['source_observation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineup_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('starter', sa.Boolean(), nullable=True),
    sa.Column('is_goalkeeper', sa.Boolean(), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('jersey', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['lineup_snapshot_id'], ['lineup_snapshot.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prediction_run', sa.Column('input_quality_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_run', 'input_quality_json')
    op.drop_table('lineup_entry')
    op.drop_table('lineup_snapshot')
    op.drop_table('player')
    # ### end Alembic commands ###
