"""fixture scores

Revision ID: 5be6d33aeb20
Revises: 3b45f6f49303
Create Date: 2026-07-23 00:29:16.142213
"""
from alembic import op
import sqlalchemy as sa


revision = '5be6d33aeb20'
down_revision = '3b45f6f49303'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture', sa.Column('home_goals', sa.Integer(), nullable=True))
    op.add_column('fixture', sa.Column('away_goals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixture', 'away_goals')
    op.drop_column('fixture', 'home_goals')
    # ### end Alembic commands ###
