"""paper trading ledger (V8.1 eval Phase 7 / step 8)

PAPER-only execution ledger: signals (incl. rejections) + simulated
fills against frozen books. New tables, plain CREATE — both dialects.

Revision ID: 755ded7a27ff
Revises: 521bd3137595
Create Date: 2026-07-23 11:40:24.579114
"""
from alembic import op
import sqlalchemy as sa


revision = '755ded7a27ff'
down_revision = '521bd3137595'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_run_id', sa.String(length=36), nullable=False),
    sa.Column('market_contract_id', sa.Integer(), nullable=True),
    sa.Column('market_quote_id', sa.Integer(), nullable=True),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('outcome_key', sa.String(length=32), nullable=True),
    sa.Column('policy_version', sa.String(length=24), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('ask_c', sa.Integer(), nullable=True),
    sa.Column('fee_c', sa.Integer(), nullable=True),
    sa.Column('net_edge', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=12), nullable=True),
    sa.Column('reject_reason', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.ForeignKeyConstraint(['market_contract_id'], ['market_contract.id'], ),
    sa.ForeignKeyConstraint(['market_quote_id'], ['market_quote.id'], ),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_run_id', 'market_contract_id', name='uq_paper_signal_run_contract')
    )
    op.create_table('paper_fill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_signal_id', sa.Integer(), nullable=False),
    sa.Column('requested_contracts', sa.Integer(), nullable=True),
    sa.Column('filled_contracts', sa.Integer(), nullable=True),
    sa.Column('avg_fill_price_c', sa.Integer(), nullable=True),
    sa.Column('best_ask_c', sa.Integer(), nullable=True),
    sa.Column('slippage_c', sa.Integer(), nullable=True),
    sa.Column('fee_c', sa.Integer(), nullable=True),
    sa.Column('cost_c', sa.Integer(), nullable=True),
    sa.Column('levels_consumed', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('outcome_hit', sa.Boolean(), nullable=True),
    sa.Column('payout_c', sa.Integer(), nullable=True),
    sa.Column('pnl_c', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_signal_id'], ['paper_signal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_fill')
    op.drop_table('paper_signal')
    # ### end Alembic commands ###
