"""lock policy manifest + approval record (V8.1 eval qualifications)

Additive nullable columns only — plain ADD COLUMN is valid on both
SQLite and PostgreSQL, no batch/table-rewrite needed. Existing rows
keep NULL for the new fields (they predate the policy).

Revision ID: 9673668959a8
Revises: 8329bc9afacb
Create Date: 2026-07-23 09:42:44.989874
"""
from alembic import op
import sqlalchemy as sa


revision = '9673668959a8'
down_revision = '8329bc9afacb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_snapshot', sa.Column('policy_version', sa.String(length=24), nullable=True))
    op.add_column('market_snapshot', sa.Column('quotes_with_prices', sa.Integer(), nullable=True))
    op.add_column('market_snapshot', sa.Column('quotes_without_prices', sa.Integer(), nullable=True))
    op.add_column('market_snapshot', sa.Column('oldest_quote_age_seconds', sa.Integer(), nullable=True))
    op.add_column('market_snapshot', sa.Column('required_families_complete', sa.Boolean(), nullable=True))
    op.add_column('market_snapshot', sa.Column('execution_ready', sa.Boolean(), nullable=True))
    op.add_column('prediction_run', sa.Column('model_approved_at_run', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_run', 'model_approved_at_run')
    op.drop_column('market_snapshot', 'execution_ready')
    op.drop_column('market_snapshot', 'required_families_complete')
    op.drop_column('market_snapshot', 'oldest_quote_age_seconds')
    op.drop_column('market_snapshot', 'quotes_without_prices')
    op.drop_column('market_snapshot', 'quotes_with_prices')
    op.drop_column('market_snapshot', 'policy_version')
    # ### end Alembic commands ###
